CREATE TABLE IF NOT EXISTS SIMULATION.TRANSFER (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  DATE TIMESTAMP NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  VALUE DECIMAL(19,5) NOT NULL,
  VERSION INT default 0,
  TYPE VARCHAR(10),
  REVERT_TRANSFER_ID INT ,
  ORIGIN_ACCOUNT_FK INT NOT NULL,
  DESTINATION_ACCOUNT_FK INT NOT NULL,
  foreign key (REVERT_TRANSFER_ID) references SIMULATION.TRANSFER(ID),
  foreign key (ORIGIN_ACCOUNT_FK) references SIMULATION.ACCOUNT(ID),
  foreign key (DESTINATION_ACCOUNT_FK) references SIMULATION.ACCOUNT(ID)
);