CREATE TABLE IF NOT EXISTS SIMULATION.ACCOUNT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  AGENCY VARCHAR(10) NOT NULL,
  NUMBER varchar(10) NOT NULL,
  DIGIT varchar(3) NOT NULL,
  BALANCE DECIMAL(19,5) default 0,
  BANK_FK int NOT NULL,
  foreign key (BANK_FK) references SIMULATION.BANK(ID)
);

INSERT INTO SIMULATION.ACCOUNT (AGENCY, NUMBER, DIGIT, BANK_FK, BALANCE) VALUES ('4421', '01520446', '9', (select id from SIMULATION.BANK where CODE = '001'), 589.23);
INSERT INTO SIMULATION.ACCOUNT (AGENCY, NUMBER, DIGIT, BANK_FK, BALANCE) VALUES ('5817', '82516', '8', (select id from SIMULATION.BANK where CODE = '341'), 1008.87);
INSERT INTO SIMULATION.ACCOUNT (AGENCY, NUMBER, DIGIT, BANK_FK, BALANCE) VALUES ('4178', '01614622', '4', (select id from SIMULATION.BANK where CODE = '104'), 984.82);