CREATE TABLE IF NOT EXISTS SIMULATION.BANK (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CODE VARCHAR(6) NOT NULL UNIQUE,
  VERSION INT default 0,
  DESCRIPTION VARCHAR(250) 
);

INSERT INTO SIMULATION.BANK (CODE, DESCRIPTION) VALUES('001', 'BANCO DO BRASIL');
INSERT INTO SIMULATION.BANK (CODE, DESCRIPTION) VALUES('341', 'ITAÚ');
INSERT INTO SIMULATION.BANK (CODE, DESCRIPTION) VALUES('104', 'CAIXA ECONÔMICA FEDERAL');
INSERT INTO SIMULATION.BANK (CODE, DESCRIPTION) VALUES('033', 'SANTANDER');
INSERT INTO SIMULATION.BANK (CODE, DESCRIPTION) VALUES('237', 'BRADESCO');