CREATE TABLE IF NOT EXISTS SIMULATION.ACCOUNT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  AGENCY VARCHAR(10) NOT NULL,
  DIGIT_AGENCY VARCHAR(3),
  NUMBER varchar(10) NOT NULL,
  DIGIT varchar(3) NOT NULL,
  ACCOUNT_TYPE int NOT NULL,
  BANK_FK int NOT NULL,
  foreign key (BANK_FK) references SIMULATION.BANK(ID)
);

INSERT INTO SIMULATION.ACCOUNT (AGENCY, DIGIT_AGENCY, NUMBER, DIGIT, BANK_FK, ACCOUNT_TYPE) VALUES ('4421', null, '01520446', '9', (select id from SIMULATION.BANK where CODE = '001'), 1);
INSERT INTO SIMULATION.ACCOUNT (AGENCY, DIGIT_AGENCY, NUMBER, DIGIT, BANK_FK, ACCOUNT_TYPE) VALUES ('5817', null, '82516', '8', (select id from SIMULATION.BANK where CODE = '341'), 1);
INSERT INTO SIMULATION.ACCOUNT (AGENCY, DIGIT_AGENCY, NUMBER, DIGIT, BANK_FK, ACCOUNT_TYPE) VALUES ('4178', null, '01614622', '4', (select id from SIMULATION.BANK where CODE = '104'), 2);