CREATE TABLE IF NOT EXISTS SIMULATION.TRANSFER (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  DATE TIMESTAMP NOT NULL,
  VALUE varchar(10) NOT NULL,
  ORIGIN_ACCOUNT_FK INT NOT NULL,
  DESTINATION_ACCOUNT_FK INT NOT NULL,
  foreign key (ORIGIN_ACCOUNT_FK) references SIMULATION.ACCOUNT(ID),
  foreign key (DESTINATION_ACCOUNT_FK) references SIMULATION.ACCOUNT(ID)
);